name: Deploy Frontend to Firebase Hosting
on:
  push:
    branches:
      - main
    paths:
      - 'GameVault.Client/**'
      - 'GameVault.Shared/**'
      - '.github/workflows/firebase-hosting-merge.yml'
  pull_request:
    paths:
      - 'GameVault.Client/**'
      - 'GameVault.Shared/**'
      - '.github/workflows/firebase-hosting-merge.yml'
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Publish Client
        run: dotnet publish -c Release -o release GameVault.Client/GameVault.Client.csproj
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAMEVAULT_9A27E }}
          channelId: ${{ github.event_name == 'pull_request' && '' || 'live' }}
          projectId: gamevault-9a27e
